# Generated by Django 4.2 on 2023-06-01 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gastos_Grupo',
            fields=[
                ('grupoGasto_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('nome_gasto', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Gasto_grupo',
                'verbose_name_plural': 'Gastos_grupos',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('grupo_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('criador', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
            },
        ),
        migrations.CreateModel(
            name='Iten_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=9, max_digits=15)),
            ],
            options={
                'verbose_name': 'Item_Usuario',
                'verbose_name_plural': 'Itens_Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Itens',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=19)),
                ('preco_total_item', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descricao', models.CharField(max_length=255, null=True)),
                ('quantidade', models.IntegerField(blank=True, default=1)),
                ('id_GastosGrupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Grupos.gastos_grupo')),
                ('usuario', models.ManyToManyField(related_name='user_itens', through='Grupos.Iten_User', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
            },
        ),
        migrations.AddField(
            model_name='iten_user',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grupos.itens'),
        ),
        migrations.AddField(
            model_name='iten_user',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GrupoGasto_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago', models.BooleanField()),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grupos.gastos_grupo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GrupoGasto_User',
                'verbose_name_plural': 'GrupoGastos_Users',
            },
        ),
        migrations.CreateModel(
            name='Grupo_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grupos.grupo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grupo_User',
                'verbose_name_plural': 'Grupos_Users',
            },
        ),
        migrations.AddField(
            model_name='grupo',
            name='usuario',
            field=models.ManyToManyField(related_name='group_user', through='Grupos.Grupo_User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gastos_grupo',
            name='id_grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Grupos.grupo'),
        ),
        migrations.AddField(
            model_name='gastos_grupo',
            name='usuario',
            field=models.ManyToManyField(related_name='GrupoGasto_User', through='Grupos.GrupoGasto_User', to=settings.AUTH_USER_MODEL),
        ),
    ]
