# Generated by Django 4.1.7 on 2023-05-08 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Grupos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iten_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=9, max_digits=15)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grupos.itens')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='itens',
            name='usuario',
            field=models.ManyToManyField(related_name='user_itens', through='Grupos.Iten_User', to=settings.AUTH_USER_MODEL),
        ),
    ]
