# Generated by Django 4.1.7 on 2023-05-08 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grupos', '0002_iten_user_itens_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gastos_grupo',
            options={'verbose_name': 'Gasto_grupo', 'verbose_name_plural': 'Gastos_grupos'},
        ),
        migrations.AlterModelOptions(
            name='grupo',
            options={'verbose_name': 'Grupo', 'verbose_name_plural': 'Grupos'},
        ),
        migrations.AlterModelOptions(
            name='iten_user',
            options={'verbose_name': 'Item_Usuario', 'verbose_name_plural': 'Itens_Usuarios'},
        ),
    ]
