# Generated by Django 4.1.7 on 2023-05-08 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grupos', '0003_alter_gastos_grupo_options_alter_grupo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itens',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Itens'},
        ),
    ]
