# Generated by Django 4.1.7 on 2023-05-14 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grupos', '0007_remove_grupo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='grupo_id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
