# Generated by Django 4.1.7 on 2023-05-14 23:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Grupos', '0008_alter_grupo_grupo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='grupo_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
