# Generated by Django 4.1.7 on 2023-05-14 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grupos', '0009_alter_grupo_grupo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastos_grupo',
            name='nome_gasto',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
