# Generated by Django 4.1.7 on 2023-05-15 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grupos', '0010_gastos_grupo_nome_gasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='itens',
            name='descricao',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
