# Generated by Django 4.1.7 on 2023-05-15 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grupos', '0011_itens_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupogasto_user',
            old_name='item',
            new_name='conta',
        ),
    ]
