# Generated by Django 4.1.7 on 2023-05-16 20:15

import Grupos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Grupos', '0012_rename_item_grupogasto_user_conta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='usuario',
        ),
        migrations.AddField(
            model_name='grupo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Grupos.models.upload_image_book),
        ),
        migrations.AlterField(
            model_name='gastos_grupo',
            name='usuario',
            field=models.ManyToManyField(related_name='grupoGasto_user', through='Grupos.GrupoGasto_User', to=settings.AUTH_USER_MODEL),
        ),
    ]
