# Generated by Django 4.1.7 on 2023-05-16 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Grupos', '0013_remove_grupo_usuario_grupo_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='image',
        ),
        migrations.AlterField(
            model_name='gastos_grupo',
            name='usuario',
            field=models.ManyToManyField(related_name='GrupoGasto_User', through='Grupos.GrupoGasto_User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Grupo_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grupos.grupo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grupo_User',
                'verbose_name_plural': 'Grupos_Users',
            },
        ),
        migrations.AddField(
            model_name='grupo',
            name='usuario',
            field=models.ManyToManyField(related_name='group_user', through='Grupos.Grupo_User', to=settings.AUTH_USER_MODEL),
        ),
    ]
