# Generated by Django 4.2 on 2023-05-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grupos', '0014_remove_grupo_image_alter_gastos_grupo_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itens',
            name='quantidade',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
