# Generated by Django 4.2 on 2023-05-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grupos', '0015_itens_quantidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itens',
            old_name='preco',
            new_name='preco_unitario',
        ),
        migrations.AddField(
            model_name='itens',
            name='preco_total_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
