# Generated by Django 4.2 on 2023-05-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grupos', '0016_rename_preco_itens_preco_unitario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos_grupo',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
    ]
