# Generated by Django 4.2 on 2023-05-18 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grupos', '0017_alter_gastos_grupo_valor_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupo_user',
            old_name='item',
            new_name='grupo',
        ),
    ]
