# Generated by Django 4.2 on 2023-05-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grupos', '0018_rename_item_grupo_user_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='criador',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
