# Generated by Django 4.2 on 2023-05-22 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Grupos", "0020_merge_0015_grupouser_0019_grupo_criador"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GrupoUser",
        ),
    ]
