runserver:
	python manage.py runserver --settings=GUMA_investimentos.local_settings

makemigrations:
	python manage.py makemigrations --settings=GUMA_investimentos.local_settings

migrate:
	python manage.py migrate --settings=GUMA_investimentos.local_settings