# Generated by Django 4.2 on 2023-06-01 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bancario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('saldo_atual', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date', models.DateField()),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Saldos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date', models.DateTimeField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('id_bancario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Bancario.bancario')),
            ],
        ),
    ]
