# Generated by Django 4.2 on 2023-05-25 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bancario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saldos',
            old_name='id_grupo',
            new_name='id_bancario',
        ),
    ]
