# Generated by Django 4.2 on 2023-06-16 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bancario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saldos',
            name='nome',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
