# Generated by Django 4.2 on 2023-05-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bancario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saldos',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
