# Generated by Django 4.2 on 2023-05-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bancario', '0002_saldos_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldos',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
