# Generated by Django 4.2 on 2023-06-16 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Grupos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Debitos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20)),
                ('devedores', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_devedor', to=settings.AUTH_USER_MODEL)),
                ('dono', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_dono', to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grupos.itens')),
            ],
        ),
    ]
