# Generated by Django 4.2 on 2023-06-19 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Grupos', '0002_gastos_grupo_provedor'),
        ('DebGroup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debitos',
            old_name='devedores',
            new_name='devedor',
        ),
        migrations.RenameField(
            model_name='debitos',
            old_name='grupo',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='debitos',
            old_name='dono',
            new_name='provedor',
        ),
        migrations.AddField(
            model_name='debitos',
            name='grupo_gasto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Grupos.gastos_grupo'),
            preserve_default=False,
        ),
    ]
