# Generated by Django 4.2 on 2023-04-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gasto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=9)),
                ("data", models.DateField()),
                ("pago", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Gasto",
                "verbose_name_plural": "Gastos",
            },
        ),
    ]
