# Generated by Django 4.1.7 on 2023-04-25 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Gastos', '0004_gasto_user_alter_gasto_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='valor',
            field=models.FloatField(),
        ),
    ]
