# Generated by Django 4.2 on 2023-06-22 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacaoManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('valor', models.FloatField()),
                ('data', models.DateTimeField()),
                ('pago', models.BooleanField(blank=True, default=False, null=True)),
                ('tag', models.CharField(blank=True, max_length=255, null=True)),
                ('atualizacao', models.DateTimeField()),
                ('frequencia', models.CharField(max_length=1)),
                ('tipo', models.CharField(max_length=1)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'Recorrente',
                'verbose_name_plural': 'Recorrentes',
            },
        ),
    ]
